version: 2
jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run typescript checker
          command: npx tsc --noEmit
      - run:
          name: Run tslint
          command: npm run tslint
      - run:
          name: Build application
          command: npm run build
      - run:
          name: Run tests
          command: npm run test
      - persist_to_workspace:
          root: ~/app
          paths:
            - dist/*
      - run:
          name: Running E2E tests
          command: npm run test:e2e:run
      - store_test_results:
          path: multiple-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  deploy:
    working_directory: ~/app
    docker:
      - image: cypress/base:10
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Npm CI
          command: npm ci
      - run:
          command: npx cypress verify
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .cache/Cypress
      - attach_workspace:
          at: ~/
      - run:
          name: Run Cypress tests
          command: "npx cypress run"
workflows:
  build:
    jobs:
      - cypress/run
  version: 2
